services:
  gts-db:
    image: postgres:13.3
    command: postgres -c 'max_connections=256'
    container_name: gts-db
    environment:
      POSTGRES_USER: gts
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: gts
    ports:
      - "$DATABASE_PORT_PORT:5432"
    restart: always
    volumes:
      - gts-db-data:/var/lib/postgresql/data/

volumes:
  gts-db-data:
