// <auto-generated />
using GreenTechSee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenTechSee.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922131439_AddCompany")]
    partial class AddCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenTechSee.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("GreenTechSee.Companies.CompanyCredential", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyCredentials");
                });

            modelBuilder.Entity("GreenTechSee.Companies.CompanySocialMedia", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.HasKey("CompanyId", "Id");

                    b.ToTable("CompanySocialMedias");
                });

            modelBuilder.Entity("GreenTechSee.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AfterApprenticeShip")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Line")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<int?>("WantedTrade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GreenTechSee.Students.StudentCertificates", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("StudentId", "Id");

                    b.ToTable("StudentCertificates");
                });

            modelBuilder.Entity("GreenTechSee.Students.StudentCredential", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.ToTable("StudentCredentials");
                });

            modelBuilder.Entity("GreenTechSee.Students.StudentSocialMedia", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.HasKey("StudentId", "Id");

                    b.ToTable("StudentSocialMedias");
                });

            modelBuilder.Entity("GreenTechSee.Companies.CompanyCredential", b =>
                {
                    b.HasOne("GreenTechSee.Companies.Company", "Company")
                        .WithOne("CompanyCredential")
                        .HasForeignKey("GreenTechSee.Companies.CompanyCredential", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GreenTechSee.Companies.CompanySocialMedia", b =>
                {
                    b.HasOne("GreenTechSee.Companies.Company", "Company")
                        .WithMany("mediaLinks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GreenTechSee.Students.StudentCertificates", b =>
                {
                    b.HasOne("GreenTechSee.Students.Student", "Student")
                        .WithMany("Certificates")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GreenTechSee.Students.StudentCredential", b =>
                {
                    b.HasOne("GreenTechSee.Students.Student", "Student")
                        .WithOne("Credential")
                        .HasForeignKey("GreenTechSee.Students.StudentCredential", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GreenTechSee.Students.StudentSocialMedia", b =>
                {
                    b.HasOne("GreenTechSee.Students.Student", "Student")
                        .WithMany("MediaLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GreenTechSee.Companies.Company", b =>
                {
                    b.Navigation("CompanyCredential");

                    b.Navigation("mediaLinks");
                });

            modelBuilder.Entity("GreenTechSee.Students.Student", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Credential");

                    b.Navigation("MediaLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
